services:
  - type: web
    name: richman-tours
    env: python
    plan: free  # Explicitly specify free plan
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn richman_tours.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: richman-tours-db
          property: connectionString

databases:
  - name: richman-tours-db
    plan: free  # Explicitly specify free plan
    databaseName: richman_tours
    user: richman_tours_user