# Generated by Django 4.2.23 on 2025-08-15 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total_amount',
            new_name='estimated_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.CharField(default='Custom Destination', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tour'),
        ),
    ]
